/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ldxxcwitonibkeaxyeqi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkeHhjd2l0b25pYmtlYXh5ZXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMTQ5OTYsImV4cCI6MjA3ODY5MDk5Nn0.vXa0bwTxGAapWpQY4VCcK4tiJrY9CDTKYcz-YfA-Ks8"